Brief/Controllers/BriefDatasController.cs
using Brief.Data;
using Brief.Models;
using Brief.Services;

using DinkToPdf;
using DinkToPdf.Contracts;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Brief.Controllers
{
    public class BriefDatasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConverter pdfConverter;

        public BriefDatasController(ApplicationDbContext context, IConverter pdfConverter)
        {
            _context = context;
            this.pdfConverter = pdfConverter;
        }

        // GET: BriefDatas
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.BriefDatas.ToListAsync());
        }

        // GET: BriefDatas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BriefDatas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Customer,Contacts,HaveWebSite,FinalGoals,AdditionalGoals,Niche,GrowthPoints,Uniqueness,Examples,DemographicData,PerfectClient,ProblemsAndMotives,BrendElements,LikeAndDoNotLikeExamples,Emotions,BrendBook,Ideas,Copyright,ClientMaterials,PaidOrFree,List,ReadyIntegrations,FeaturesToContactWithClient,Blog,ClientPath,Pages,MinimalisticOrDetailed,Functions,Content,BudgetAndDeadlines1,HelpAfterRelease,ContactPerson,ContactStages,IsDeployNeeded,Domain")] BriefData briefData)
        {
            if (ModelState.IsValid)
            {
                var date = DateTime.Now;
                briefData.CreatedDate = date;
                briefData.LastModifiedDate = date;
                _context.Add(briefData);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Success));
            }
            return View(briefData);
        }

        public IActionResult Success()
        {
            return View();
        }

        // GET: BriefDatas/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var briefData = await _context.BriefDatas.FindAsync(id);
            if (briefData == null)
            {
                return NotFound();
            }
            return View(briefData);
        }

        // POST: BriefDatas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Customer,Contacts,HaveWebSite,FinalGoals,AdditionalGoals,Niche,GrowthPoints,Uniqueness,Examples,DemographicData,PerfectClient,ProblemsAndMotives,BrendElements,LikeAndDoNotLikeExamples,Emotions,BrendBook,Ideas,Copyright,ClientMaterials,PaidOrFree,List,ReadyIntegrations,FeaturesToContactWithClient,Blog,ClientPath,Pages,MinimalisticOrDetailed,Functions,Content,BudgetAndDeadlines1,HelpAfterRelease,ContactPerson,ContactStages,IsDeployNeeded,Domain")] BriefData briefData)
        {
            if (id != briefData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var brief = _context.BriefDatas.AsNoTracking().FirstOrDefault(e => e.Id == id);
                    if (brief == null)
                        return NotFound();

                    briefData.CreatedDate = brief.CreatedDate;
                    briefData.LastModifiedDate = DateTime.Now;

                    _context.Update(briefData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BriefDataExists(briefData.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(briefData);
        }

        // GET: BriefDatas/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var briefData = await _context.BriefDatas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (briefData == null)
            {
                return NotFound();
            }

            return View(briefData);
        }

        // POST: BriefDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var briefData = await _context.BriefDatas.FindAsync(id);
            if (briefData != null)
            {
                _context.BriefDatas.Remove(briefData);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Download(int id)
        {
            var briefData = await _context.BriefDatas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (briefData == null)
            {
                return NotFound();
            }

            var globalSettings = new GlobalSettings
            {
                ColorMode = ColorMode.Color,
                Orientation = Orientation.Portrait,
                PaperSize = PaperKind.A4,
                Margins = new MarginSettings { Top = 10 },
                DocumentTitle = $"Brief Result {briefData.Id}",
            };

            var objectSettings = new ObjectSettings
            {
                PagesCount = true,
                HtmlContent = PdfService.GetBriefHtml(briefData),
                WebSettings = { DefaultEncoding = "utf-8", UserStyleSheet = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "css", "PdfPage.css") },
            };

            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = globalSettings,
                Objects = { objectSettings }
            };

            var file = pdfConverter.Convert(pdf);

            return File(file, "application/pdf", "EmployeeReport.pdf");
        }

        private bool BriefDataExists(int id)
        {
            return _context.BriefDatas.Any(e => e.Id == id);
        }
    }
}

Brief/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Brief</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Brief.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Brief</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BriefDatas" asp-action="Index">Брифи</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Brief - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>